### PR TITLE
Added: Currency convertion in send screen

### PR DESCRIPTION
**Pull request by iosdevashok**

### CODE REVIEW

**Comment by iosdevashok** [comment]
https://github.com/pellartech/carbon-ios/assets/102407838/0c00260f-eb1f-488b-bf39-6bc0b0110156

**Review by madtocc — CHANGES_REQUESTED** [review]
This current approach despite doing its job is a bit problematic:
1 - you send multiple GET requests to retrieve an amount, there's no debouncing so if user types 100 it will make 3 requests.
2 - The price is the same for the token, there's no need to call the API

Implementation should be: 
Create a dictionary with the token:value
- When a token is selected check dictionary if key does not exist:
  - display the skeleton view while it is loading
  - fetch the amount for 1 unit
  - Store as a dictionary the token with the value for 1 unit
  - hide skeleton view and show value as amount * value 
 
if available:
- multiply the amount * value

**Comment by iosdevashok** [comment]
https://github.com/pellartech/carbon-ios/assets/102407838/2c38bf34-005c-45f8-a29b-53563dbd7cd4

**Comment by iosdevashok** [comment]
https://github.com/pellartech/carbon-ios/assets/102407838/e819c549-e2f7-4fbe-9023-3965fcbf48f1

**Comment by iosdevashok** [comment]
https://github.com/pellartech/carbon-ios/assets/102407838/e2cc93ce-92b9-4cd7-93f6-5082c46eee3f

**Review by madtocc — APPROVED** [review]

**Pull request merged**
