### PR TITLE
Fixed - tweaks for send

### PR DESCRIPTION
**Pull request by iosdevashok**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

### Description
TODO

### Pull requests checks where applicable
- [ ] Fill in the three TODOs above (tickets number and description of your work)
- [ ] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by iosdevashok** [comment]
https://github.com/pellartech/carbon-ios/assets/102407838/d891b8c3-13f7-4898-8a0f-74cc82b4f113

**Comment by madtocc** [comment]
1 - Recipient address should indicate that the address is not valid when you try to send it and it does no go to the next page.
image

**Comment by madtocc** [comment]
4. I am sending CSIX but it sends BNB?
image
image

**Comment by madtocc** [comment]
5 - After sending you should show the transaction hash, you can place it under gas. Both gas and hash should be retrieved from your send response. When you share it should share the hash which is the proof just sending a message.
The hash is as the following: you should append the explorer to the current network.

```
enum BlockchainNetwork {
    case ethereum
    case ethereumGoerli
    case ethereumSepolia
    case bsc
    case bscTestnet
    case kucoin
    case okex
    case polygon
    case solana
}

func transactionURL(for hash: String, on network: BlockchainNetwork) -> URL? {
    let base: String
    switch network {
    case .ethereum:
        base = "https://etherscan.io/tx/"
    case .ethereumGoerli:
        base = "https://goerli.etherscan.io/tx/"
    case .ethereumSepolia:
        base = "https://sepolia.etherscan.io/tx/"
    case .bsc:
        base = "https://bscscan.com/tx/"
    case .bscTestnet:
        base = "https://testnet.bscscan.com/tx/"
    case .kucoin:
        base = "https://explorer.kcc.io/en/tx/"
    case .okex:
        base = "https://www.oklink.com/okexchain/tx/"
    case .polygon:
        base = "https://polygonscan.com/tx/"
    case .solana:
        base = "https://explorer.solana.com/tx/"
    }
    
    return URL(string: base + hash)
}


```

**Comment by iosdevashok** [comment]
https://github.com/pellartech/carbon-ios/assets/102407838/d561aafb-7660-4c31-aab0-b04ee05b492d

**Comment by iosdevashok** [comment]
IMAGE 2023-07-21 20:35:18

**Review by madtocc — APPROVED** [review]

**Pull request merged**
